### ISSUE TITLE
Adding payloads to single job

### ISSUE THREAD

**Issue by jamesholcomb** [saintedlama/microq#2]
How can I add (i.e. append) payloads to a single job before it has run?   In my use case, I am capturing dynamic event data, queueing it up on demand, and then accessing it within the job on some interval.

For example: 

`q.enqueue('myjob', { foo: 1})`
...later
`q.enqueue('myjob', { foo: 2})`

Then in `myjob` function, access both { foo: 1 } and { foo: 2 }

**Comment by saintedlama** [comment]
For your use case a job scheduler is better suited than a job queue as microq. You could use something like agenda (https://www.npmjs.com/package/agenda) or node-schedule (https://www.npmjs.com/package/node-schedule) to query a mongodb collection where you store your dynamic event data and periodically query, process and update the event data.
